name: Build Arcana Beta APK

on:
  push:
      branches: [ main ] # Se sua branch se chamar 'master', mude aqui!

      jobs:
        build:
            runs-on: ubuntu-latest
                steps:
                      - name: Checkout do Código
                              uses: actions/checkout@v4

                                    - name: Configurar Java 17
                                            uses: actions/setup-java@v4
                                                    with:
                                                              java-version: '17'
                                                                        distribution: 'temurin'

                                                                              - name: Instalar Dependências
                                                                                      run: npm install

                                                                                            - name: Build do Next.js
                                                                                                    run: npm run build

                                                                                                          - name: Inicializar e Sincronizar Capacitor
                                                                                                                  run: |
                                                                                                                            if [ ! -d "android" ]; then
                                                                                                                                        npx cap add android
                                                                                                                                                  fi
                                                                                                                                                            npx cap sync android

                                                                                                                                                                  - name: Compilar APK (Debug)
                                                                                                                                                                          run: |
                                                                                                                                                                                    cd android && ./gradlew assembleDebug

                                                                                                                                                                                          - name: Disponibilizar APK v0.1.2-beta
                                                                                                                                                                                                  uses: actions/upload-artifact@v4
                                                                                                                                                                                                          with:
                                                                                                                                                                                                                    name: Arcana-v0.1.2-beta
                                                                                                                                                                                                                              path: android/app/build/outputs/apk/debug/app-debug.apk